"""补充40味倪海厦skill药物 - 药味库缺失药物"""
import json

with open('assets/data/herbs.json','r',encoding='utf-8') as f:
    data = json.load(f)
herbs = data['herbs']
names = set(h['name'] for h in herbs)

NEW_HERBS = [
    # === 核心药 ===
    {"name":"柴胡","original":"味苦，性平，无毒。发表清热要药，散三焦肝胆诸经之热邪，主治寒热疟疾，口苦耳聋，头痛眩晕。","action":"柴胡为少阳要药，疏肝解郁，发表清热。","dosage":"普通八分至一钱，大剂三四钱。小朋友一钱，体格大两三钱。","contraindication":"凡虚人气升呕吐，及阴虚火热炎上者忌。","clinical_notes":"倪海厦：柴胡是少阳的药，属半表半里。苦味能泄能燥能坚，常用来疏肝。肝属木不能长得太密，柴胡疏肝解郁。入三焦、心包，用于淋巴系统或内分泌系统不平衡。肝胆病、脾脏病、肝癌、肝硬化、胆结石都会用到柴胡。银柴胡治骨蒸更佳。小柴胡汤（柴胡+黄芩+半夏+人参+生姜+甘草+大枣）。","nature_category":"平","flavor":"苦","meridians":["肝","胆","三焦"],"category":"解表药","historical_notes":"","herb_comparisons":["小柴胡汤（柴胡+黄芩+半夏+人参+生姜+甘草+大枣）","胁痛加青皮川芎白芍"]},
    {"name":"桂枝","original":"味辛甘，性温无毒。发表解肌要药，温经通脉，表虚中风，治手足痛风，伤寒头痛，无汗能发，有汗能止，行肺气，散寒邪，调和营卫，横通肢节。","action":"桂枝为解肌通脉要药，温经通阳，调和营卫。","dosage":"普通三分至钱半。","contraindication":"凡阴虚火炎，温病大热，喉症血症均忌。出血很多时少用。","clinical_notes":"倪海厦：名字带枝想到肢，主治四肢问题。经方60%都有桂枝。血红色、辛香、味重。桂枝主动脉（心脏到四肢末梢），芍药主静脉。治冲逆、奔豚、手臂痛风肌肉痛。桂枝入心肝助火又能利水。伤寒论使用最多的就是桂枝。","nature_category":"温","flavor":"辛甘","meridians":["心","肺","膀胱"],"category":"解表药","historical_notes":"","herb_comparisons":["桂枝汤（桂枝+白芍+生姜+甘草+大枣）","与白芍搭配调和营卫","与葛根同用发汗退热"]},
    {"name":"白芍","original":"味苦酸，性平，无毒。泻肝安脾，缓中去水要药，养血散瘀清热利肠，止腹痛，治痢疾，治胎产前后诸病，为女科良药。","action":"白芍为养血柔肝要药，敛阴止痛。","dosage":"普通二钱至五钱，大剂一两以上。","contraindication":"凡中寒腹痛，中寒作泄，肠胃中觉冷者均忌。反藜芦恶芒硝鳖甲小蓟。","clinical_notes":"倪海厦：酸味药收敛治静脉瘤。白芍味苦入血分+味酸收敛=治静脉瘤最好的药。治疗静脉瘤至少一两起。腹痛用白芍，胸满用枳实（胸满时不能用白芍，因酸收敛致静脉血回流快）。肝病用白芍（泻肝安脾）。","nature_category":"平","flavor":"苦酸","meridians":["肝","脾"],"category":"补血药","historical_notes":"","herb_comparisons":["桂枝+白芍调和营卫","四物汤组成"]},
    {"name":"桃仁","original":"味苦甘，性平，无毒。破血润燥要药，行瘀血，消心下坚硬，治血晕血痞血积血痢，血热燥痒，蓄血发狂，通月经。","action":"桃仁为破血逐瘀要药，润燥通便。","dosage":"普通一钱至二至三钱。","contraindication":"桃仁散而不收泻而无补，经闭血枯、产后血虚、大便津液不足者忌，双仁者有毒。","clinical_notes":"倪海厦：专门攻破瘀血。久咳肺有淤血用桃仁；痛经用桃仁（三钱起用）；大肠、胃里、脑部淤血都可用。肝癌用桃仁（久病必有瘀，以通为补）。带仁的药有油脂可润燥利大便。痘家勿用（仁有生气可令痘长）。","nature_category":"平","flavor":"苦甘","meridians":["心","肝","大肠"],"category":"活血化瘀药","historical_notes":"","herb_comparisons":["桃核承气汤（桃仁+桂枝+大黄+芒硝+甘草）","小柴胡汤加桃仁（伤科）"]},
    {"name":"杏仁","original":"味甘苦，性温，有小毒。咳逆痰气要药，咳嗽气急，下气平喘，治风寒痰滞，宣肺解肌，除风散寒，润燥消积，利胸膈气滞，通大肠气闭。","action":"杏仁为止咳平喘要药，宣肺润燥。","dosage":"普通钱半至三钱。入药时打碎去煮。","contraindication":"杏子性热多食致疮痈膈热，产妇尤忌，杏仁双仁者有毒，阴虚咳嗽、肺家虚热痰者忌，恶黄耆葛根。","clinical_notes":"倪海厦：肺里有痰、肺气无法宣泄，别管肺结核、肺气肿、百日咳、气喘，都可用杏仁宣肺。杏仁+麻黄是表里关系，杏仁润肺补津液，是麻黄的后备部队。吐血咳痰必用杏仁。","nature_category":"温","flavor":"甘苦","meridians":["肺","大肠"],"category":"止咳化痰药","historical_notes":"","herb_comparisons":["麻黄汤（麻黄+桂枝+杏仁+炙甘草）","桂枝加厚朴杏仁汤"]},
    {"name":"黄芪","original":"味甘，性微温，无毒。补气要药，助肺气，实皮毛，升清气，泻火气，补虚损五劳，痘疮不起，外症治痈疽，托毒止痛。","action":"黄芪为补气要药，固表托毒，利水消肿。","dosage":"生者钱半至三钱，炙者八分至三钱，大剂一二两。","contraindication":"有表邪者忌，胸膈气闭闷、肠胃有积滞者忌，阳盛阴虚者忌。","clinical_notes":"倪海厦：气药之王，补脾实脾。脾主少腹，小肚子里湿气大+脾虚用黄芪。走表固表，气不足用黄芪。太瘦用黄芪（脾主四肢肌肉）。治疮口不收口（痈疽久败疮）。通利三焦利水，虚症腹水重用黄芪。待产时重用黄芪帮助生产。平常吃黄芪美容。","nature_category":"微温","flavor":"甘","meridians":["脾","肺"],"category":"补气药","historical_notes":"","herb_comparisons":["黄芪建中汤补气","防己黄芪汤治风水"]},
    {"name":"龙胆草","original":"味苦涩，性大寒，无毒。涤邪火除湿热要药，健胃清热，治痢杀虫，主治肝火胆火胃火，下焦湿热。","action":"龙胆草为清热泻火要药，清肝胆实火，除下焦湿热。","dosage":"普通五分至钱半（倪注用三钱）。","contraindication":"胃虚血少、脾胃两虚作泻、病虚有热均忌。性大寒不可久服，恐伤胃气。","clinical_notes":"倪海厦：大苦大寒，用于重症有热症炎症时。所有热症、肝胆有火都可用。酒浸后可上行治眼疾（酒性上走）。肝经络在膀胱，可泻膀胱火。小便刺痛（热症）可用。柴胡+郁金+龙胆草治肝脏受损失眠。","nature_category":"大寒","flavor":"苦","meridians":["肝","胆","膀胱"],"category":"清热药","historical_notes":"","herb_comparisons":["柴胡+郁金+龙胆草治肝脏受损失眠","茵陈+龙胆草利湿清肝"]},
    {"name":"代赭石","original":"味苦甘，性寒，无毒。镇虚祛风，养阴血要药，避邪毒，治气逆、痰逆、反胃、血中热、血痹、血痢、女子赤白带下。","action":"代赭石为重镇降逆要药，平肝潜阳，降气化痰。","dosage":"入煎剂钱半至三钱，水飞用五分至一钱。醋淬研末水飞用。","contraindication":"下部虚寒及阳虚阴痿者忌，胎前慎用，畏天雄附子。","clinical_notes":"倪海厦：胃酸反逆看舌苔：苔黄用赭石+旋覆花（热症）；苔白不渴喜热水用吴茱萸+干姜（寒症）。赭石重镇入血分（色赤），能降血降气。旋覆花代赭石汤治胃酸反逆。","nature_category":"寒","flavor":"苦甘","meridians":["肝","胃","心包"],"category":"平肝药","historical_notes":"","herb_comparisons":["旋覆花代赭石汤（旋覆花+代赭石+半夏+生姜+甘草+人参+大枣）"]},
    {"name":"旋覆花","original":"味咸，性温，无毒。下气祛痰健胃行水要药，主治肺胃气虚、痰水胶结、上气喘急。","action":"旋覆花为降气化痰要药，消痰行水。","dosage":"普通一钱至二三钱。质轻，两三钱就很多。","contraindication":"病人涉虚者忌多服，冷利大肠，虚寒人禁用。","clinical_notes":"倪海厦：旋覆花代赭石汤主药，治胃酸。能下气治打嗝，同时行胃建水。代赭石性寒，旋覆花性温，搭配后药性不太寒。恶心吃不了东西都可用旋覆花降气，配合半夏止呕。","nature_category":"温","flavor":"咸","meridians":["肺","胃","大肠"],"category":"化痰药","historical_notes":"","herb_comparisons":["旋覆花+代赭石（核心搭配）","旋覆花+半夏+生姜降逆止呕"]},
    {"name":"赤芍","original":"味苦酸，性平，无毒。同白芍，根切开红色者名赤芍。活血散瘀，清热凉血。","action":"赤芍为清热凉血要药，活血散瘀。","dosage":"同白芍。","contraindication":"同白芍。","clinical_notes":"倪海厦：白芍赤芍功效一样，没必要区分。若硬要区分：赤芍比较着重在外面（疮家用），白芍比较着重在里面（治疗脾脏用）。赤芍、银花都是活血化瘀同时收敛伤口的。赤芍有地火之性（红色入血分）。","nature_category":"微寒","flavor":"苦","meridians":["肝","脾"],"category":"清热凉血药","historical_notes":"","herb_comparisons":["赤芍+银花活血化瘀同时收敛伤口"]},
    # === 重要药 ===
    {"name":"乌梅","original":"味酸，性平而涩。收敛、解热、消肿、驱虫之药，治久利、痢疾、反胃、去面痣、蚀恶肉、蚘厥吐利、驱蛔虫。","action":"乌梅为收敛固涩要药，生津安蛔。","dosage":"一般一钱至三钱。","contraindication":"多食损齿伤筋，风寒初起、疟痢未久者忌，忌猪肉。","clinical_notes":"倪海厦：乌梅是酸涩的，涩剂治下痢还能杀虫。最常用的就是下痢和杀虫。酸味药可解酒毒。乌梅蚀恶肉（与雄黄、铅粉同功）。乌梅捣烂贴乳房流脓处可治乳癌坏肉。有一种失眠是魂不归肝，用乌梅、酸枣仁。","nature_category":"平","flavor":"酸","meridians":["肝","脾","肺","大肠"],"category":"收涩药","historical_notes":"","herb_comparisons":[]},
    {"name":"川芎","original":"味辛，性温，无毒。顺气行血要药，行气开郁，入肝理血，上行头目，下行血海，主治头痛及妇女一切气郁血郁。","action":"川芎为行气活血要药，祛风止痛。","dosage":"普通三分至钱半。治病大剂可到一两。","contraindication":"性疏散不宜久服，反能损肝，畏黄连伏雌黄。","clinical_notes":"倪海厦：遇到肝病（B肝C肝肝硬化肝癌）一定用川芎；头痛第一味药想到川芎；妇科良药。阿司匹林是酸寒的使血管收缩，大剂量川芎可恢复正常血液循环。甲状腺结节可用川芎。四川产者为佳。","nature_category":"温","flavor":"辛","meridians":["肝","胆","心包"],"category":"活血化瘀药","historical_notes":"","herb_comparisons":["四物汤（当归+川芎+白芍+生地）","单味川芎粉外敷治关节肿大"]},
    {"name":"肉桂","original":"味辛甘，性大热，有小毒。温补要药，扶火助阳，温中逐寒，引火归元，治上热下寒，破沉寒痼冷。","action":"肉桂为温补命门要药，引火归元。","dosage":"普通三分至一钱（冲服）。生用冲服力更大。","contraindication":"忌生葱石脂及火炙，阴虚内热液少口干者慎用。","clinical_notes":"倪海厦：桂枝入血脉，肉桂入心脏肾脏。肾脏火不够或命门火不够用肉桂。大热药，脸色红润舌苔黄者吃肉桂易便秘，寒凉体质才可用。肉桂打粉冲服效果最好。肉桂+附子=点火+固阳。命门火在人就不会死。","nature_category":"大热","flavor":"辛甘","meridians":["肾","脾","心","肝"],"category":"温里药","historical_notes":"","herb_comparisons":["肉桂+附子（桂附八味丸）","桂枝汤加肉桂粉冲服"]},
    {"name":"芒硝","original":"味苦，性寒，无毒。清积热利小便，治五淋。五脏积热，胃张闭，涤去蓄结饮食，推陈致新。","action":"芒硝为软坚散结要药，泻热通便。","dosage":"普通五分至一钱。煎剂后下。","contraindication":"性峻，孕妇忌。","clinical_notes":"倪海厦：芒硝是攻坚的药（与大黄消炎不同）。大便燥结加芒硝打散。遇到对证时用大黄芒硝攻下，对病人来说是补药。经方中大黄去实+芒硝攻坚。煎剂后下（先煮大黄炙甘草，去滓后内芒硝微煮令沸）。","nature_category":"寒","flavor":"苦","meridians":["胃","大肠","三焦"],"category":"泻下药","historical_notes":"","herb_comparisons":["调胃承气汤（大黄+炙甘草+芒硝）","大承气汤（厚朴+枳实+大黄+芒硝）"]},
    {"name":"硫磺","original":"味酸，性温（实为大热），有毒。补阳要药，主治脾胃虚寒、寒痹冷癖、命门火衰，发汗祛寒痰，疏利大肠，杀虫治疮疥。","action":"硫磺为补火助阳要药，杀虫止痒。","dosage":"普通五分至二钱。重症可重用（棉布包煮）。","contraindication":"中病便止，畏细辛朴消。中毒出红疹吃鸭肉可解。","clinical_notes":"倪海厦：产在火山口，比附子还热。双脚无力用硫磺（肉桂是添柴，硫磺是浇油）。入三焦利水，水肿用硫磺。生用治疥癣攻坚（如肝癌），熟用补阳虚（阳不举）。能化五金（治小便结石排不出）。金液丹回阳救逆。硫磺可燃=水中之火，体内水气化解决水肿。烫伤撒硫磺粉不留疤。","nature_category":"大热","flavor":"酸","meridians":["肾","脾","大肠"],"category":"补阳药","historical_notes":"","herb_comparisons":["硫磺+生附子（重症回阳）","硝石矾石散治黑疸"]},
    {"name":"血竭","original":"甘、咸，平。归肝经。活血定痛、化瘀止血、生肌敛疮。","action":"血竭为活血散瘀要药，收敛生肌。","dosage":"内服三分至一钱，外用适量。","contraindication":"血虚无瘀者不宜。","clinical_notes":"倪海厦：血竭用于收敛伤口，腐烂肌肉重生。外用为主。属伤科药，破血力强，血虚时慎用。伤口破裂用续断、三七、乳香、没药、血竭收敛伤口。知母黄连外敷可加血竭收敛伤口。","nature_category":"平","flavor":"甘咸","meridians":["肝","心包"],"category":"活血化瘀药","historical_notes":"","herb_comparisons":[]},
    {"name":"皂角刺","original":"味辛，性温，无毒。通关窍，消痈疽，搜风，杀虫，治风疠，腹内生疮，妇人妒乳，胎衣不下。","action":"皂角刺为消痈排脓要药，搜风通络。","dosage":"约三钱。","contraindication":"痈疽已溃者、气虚者与孕妇均禁用。","clinical_notes":"倪海厦：功同皂荚而力更锋锐，能直达病所。通风涎咽喉阻塞、治痈疽未溃均妙。倪老师遇到喉咙堵到会用皂角刺。皂角刺就是发脓疡的。","nature_category":"温","flavor":"辛","meridians":["肝","胃"],"category":"活血化瘀药","historical_notes":"","herb_comparisons":["皂荚+红枣（皂荚红枣汤清肺脓痰）"]},
    {"name":"穿山甲","original":"咸，微寒。归肝、胃经。通经下乳、消肿排脓、搜风通络。","action":"穿山甲为通经下乳要药，消肿排脓。（现代已禁用，以王不留行替代）","dosage":"一钱至三钱。现已禁用。","contraindication":"孕妇禁用。现已为禁用动物药。","clinical_notes":"倪海厦：穿山甲已为禁用动物药。现代中医多以王不留行、路路通等替代。其穿山透络、通经下乳、消肿排脓之功，可用其他药物替代。","nature_category":"微寒","flavor":"咸","meridians":["肝","胃"],"category":"活血化瘀药","historical_notes":"已禁用动物药","herb_comparisons":[]},
    {"name":"冰片","original":"辛、苦，微寒。归心、脾、肺经。开窍醒神、清热止痛。","action":"冰片为开窍醒神要药，清热止痛。","dosage":"内服三至五厘，外用适量。","contraindication":"孕妇慎用。","clinical_notes":"倪海厦：冰片辛香走窜，开窍醒神。外用治目疾、喉痹、口疮。配合麝香增强开窍之力。","nature_category":"微寒","flavor":"辛苦","meridians":["心","脾","肺"],"category":"开窍药","historical_notes":"","herb_comparisons":[]},
    {"name":"儿茶","original":"苦、涩，微寒。归肺经。收湿生肌、敛疮止血。","action":"儿茶为收湿敛疮要药，止血定痛。","dosage":"内服一至二分，外用适量。","contraindication":"","clinical_notes":"倪海厦：儿茶外用收湿敛疮，治口疮、痔疮、湿疹。内服清热化痰。","nature_category":"微寒","flavor":"苦涩","meridians":["肺"],"category":"外用药","historical_notes":"","herb_comparisons":[]},
    # === 常用药 ===
    {"name":"生地黄","original":"味甘，性寒，无毒。滋阴养血要药，凉血热，滋肝肾，养心益肺，通血脉逐血痹。","action":"生地黄为凉血滋阴要药，养血生津。","dosage":"普通二钱至四钱，大剂二三两。","contraindication":"脾胃弱、大便泄、产后不食或泻、胸膈多痰者忌，忌铜铁及茶。","clinical_notes":"倪海厦：干地黄甘寒入脾，滋补药，补骨髓长肌肉。女人用生地（补血凉血），男人用熟地（补肾补精）。阴虚=阳症（红光满面但无力），可用生地凉补。熟地色黑补肾。地黄无毒可重剂。","nature_category":"寒","flavor":"甘","meridians":["心","肝","肾"],"category":"补血药","historical_notes":"","herb_comparisons":["四物汤（当归+川芎+白芍+生地/熟地）","六味地黄丸"]},
    {"name":"牡丹皮","original":"味辛苦，性微寒，无毒。理血要药，清伏火凉血热，通月经排瘀血，主治胎前产后冷热气血之病，为女科良剂。","action":"牡丹皮为清热凉血要药，活血化瘀。","dosage":"普通一钱至三钱。","contraindication":"女子血崩及经血过期不尽者忌与行血药同用，忌蒜及芫荽铁器。","clinical_notes":"倪海厦：血症用丹皮，女子月经痛可用丹皮活血化瘀。久病必有瘀，活血化瘀原则用于重症癌症肿瘤。丹皮根入药，根性向下，泄中下焦之血。倪老师说他用丹皮用得很多。","nature_category":"微寒","flavor":"辛苦","meridians":["心","肝","肾"],"category":"清热凉血药","historical_notes":"","herb_comparisons":[]},
    {"name":"紫苏叶","original":"味辛，性温，无毒。发表散寒解毒要药，降气化痰，发汗祛寒，主伤风寒热霍乱，肺气喘急，心腹胀满，安胎。","action":"紫苏叶为解表散寒要药，行气宽中。","dosage":"叶梗八分至二钱，苏子钱半至三钱。入药不能煮太久，快出锅时再下。","contraindication":"阴虚因发寒热或寒头痛者忌，火升作呕者忌，忌鲤鱼。","clinical_notes":"倪海厦：叶子类药很轻，行气力量很强。喉咙气海堵到（梅核气）用紫苏降气化痰。入药不能煮太久（行气药煮久没力量），快出锅时再下。紫苏主散的性多、主升的性少。","nature_category":"温","flavor":"辛","meridians":["肺","脾"],"category":"解表药","historical_notes":"","herb_comparisons":[]},
    {"name":"菊花","original":"味苦甘平，无毒。清风热明目解毒要药，主诸风头眩肿痛、目痛翳膜、利血脉、治疔疮。","action":"菊花为疏风清热要药，明目解毒。","dosage":"普通一钱至三钱。","contraindication":"味苦辣者、陈久者不堪用。菊花不喜陈。","clinical_notes":"倪海厦：风寒外感头痛用菊花。生眼翳也可用。菊叶捣碎敷伤口助愈合+解毒。菊花不喜陈（大部分中药越陈越好，菊花例外）。入肝，肝病治头部眼泪过多头痛（风热上乘）。菊叶疗疮以新鲜最好。","nature_category":"平","flavor":"苦甘","meridians":["肝","肺"],"category":"清热药","historical_notes":"","herb_comparisons":[]},
    {"name":"金银花","original":"甘，寒。归肺、心、胃经。清热解毒，凉散风热。用于痈肿疔疮、喉痹、丹毒、热毒血痢、风热感冒、温病发热。","action":"金银花为清热解毒要药，凉散风热。","dosage":"质轻，一般用两钱。","contraindication":"脾胃虚寒及气虚疮疡脓清者忌服。","clinical_notes":"倪海厦：多用在皮肤病上。扁桃腺发炎加连翘银花浮萍蝉蜕。皮肤痒加连翘银花。赤芍银花活血化瘀同时收敛伤口。皮肤头面部的湿热都可加银花。","nature_category":"寒","flavor":"甘","meridians":["肺","心","胃"],"category":"清热解毒药","historical_notes":"","herb_comparisons":[]},
    {"name":"蒲公英","original":"苦、甘，寒。归肝、胃经。清热解毒，消肿散结，利尿通淋。","action":"蒲公英为清热解毒要药，消痈散结。","dosage":"三至五钱。","contraindication":"阳虚外寒、脾胃虚弱者忌。","clinical_notes":"倪海厦：蒲公英为治乳痈要药，乳腺炎红肿热痛用之。配合金银花、紫花地丁增强清热解毒之力。","nature_category":"寒","flavor":"苦甘","meridians":["肝","胃"],"category":"清热解毒药","historical_notes":"","herb_comparisons":[]},
    {"name":"紫花地丁","original":"苦、辛，寒。归心、肝经。清热解毒，凉血消肿。","action":"紫花地丁为清热解毒要药，凉血消痈。","dosage":"三至五钱。","contraindication":"体质虚寒者不宜。","clinical_notes":"倪海厦：紫花地丁为治疔毒要药，疔疮走黄用之。配合金银花、蒲公英、天葵子、野菊花即五味消毒饮。","nature_category":"寒","flavor":"苦辛","meridians":["心","肝"],"category":"清热解毒药","historical_notes":"","herb_comparisons":[]},
    {"name":"蝉蜕","original":"味甘，平，无毒。治小儿惊痫，寒热，结气，蛊毒，鬼疰。","action":"蝉蜕为疏风散热要药，透疹止痒。","dosage":"质轻，数分至一钱半。三钱一大包。","contraindication":"孕妇慎用。","clinical_notes":"倪海厦：质轻的药走皮肤表面，蝉蜕、蛇蜕走表。皮肤病用蝉蜕，鼻窦炎用辛夷花。蝉蜕三钱一大包（质轻不能开太重）。扁桃腺发炎加蝉蜕。治疟疾与皮肤病用。升阳明经津液（葛根汤加蝉蜕）。","nature_category":"平","flavor":"甘","meridians":["肺","肝"],"category":"解表药","historical_notes":"","herb_comparisons":[]},
    {"name":"陈皮","original":"味苦辛，性温，无毒。宣通疏利要药，行气健胃，去湿化痰，能发散清热，消积水气。","action":"陈皮为理气健脾要药，燥湿化痰。","dosage":"普通一钱至三钱。","contraindication":"中气虚气不归元者忌与耗气药同用，胃虚有火呕吐者忌与温热香燥药同用。","clinical_notes":"倪海厦：广陈皮（广东广西产）为佳，越陈越好。辛香温药能利水谷助消化。下气帮助食物往下走。青皮入肝脏疏肝力强，陈皮入脾胃行气健脾降气。轻度打嗝可用陈皮。凡补药涩药必用陈皮以利气，气行则领导百药。","nature_category":"温","flavor":"苦辛","meridians":["脾","肺"],"category":"理气药","historical_notes":"","herb_comparisons":["橘皮竹茹汤（橘皮+竹茹+大枣+生姜+甘草+人参）"]},
    {"name":"砂仁","original":"辛，温。归脾、胃、肾经。化湿开胃，温脾止泻，理气安胎。","action":"砂仁为化湿行气要药，温脾止泻。","dosage":"一般用一钱。","contraindication":"阴虚有热者忌服。","clinical_notes":"倪海厦：西砂仁对胃很好。分消汤中用砂仁一钱，每味剂量勿用太重（甘淡渗利原则）。砂仁配木香干姜治腹水。分消汤每味轻推才是甘淡渗利。砂仁三钱配木香三钱干姜三钱是重剂。","nature_category":"温","flavor":"辛","meridians":["脾","胃","肾"],"category":"化湿药","historical_notes":"","herb_comparisons":[]},
    # === 特殊药 ===
    {"name":"竹茹","original":"甘，微寒。清热化痰，除烦止呕。用于痰热咳嗽、胆火挟痰、烦热呕吐、惊悸失眠、胃热呕吐、妊娠恶阻。","action":"竹茹为清热化痰要药，除烦止呕。","dosage":"1.5至3钱。","contraindication":"胃寒呕吐及感寒挟食作吐者忌用。","clinical_notes":"倪海厦：竹茹象筋脉，能清络脉里的热。平常用竹茹让胃热凉下来。治口渴严重（吐了胃津液）。竹茹通利三焦去湿，类似防己。治糖尿病常用。三焦系统、淋巴系统、腮腺甲状腺乳房硬块都可用。胃家虚热用竹茹不用芩连（非真正发炎）。","nature_category":"微寒","flavor":"甘","meridians":["肺","胃","胆"],"category":"化痰药","historical_notes":"","herb_comparisons":["橘皮竹茹汤（橘皮+竹茹+大枣+生姜+甘草+人参）治哕逆"]},
    {"name":"葶苈子","original":"味辛苦，性大寒，无毒。下气行水要药，降肺气，逐痰饮，止喘促，下膀胱水，治面目浮肿。","action":"葶苈子为泻肺平喘要药，利水消肿。","dosage":"普通八分至二三钱。入药前须炒过。","contraindication":"脾虚不能制水、膀胱虚无气者忌，肺气虚者忌，宜大枣为辅，恶僵蚕。","clinical_notes":"倪海厦：肺像天幕云彩，葶苈子让云变雨（金生水），治气喘好用。治面部水肿（水气在上）。苦寒猛药，性极速降，配大枣补之。葶苈子涤水去痰力强，所有苦味利水药中葶苈子最苦。治肺积水（甘遂半夏汤、十枣汤、葶苈大枣泻肺汤）。","nature_category":"大寒","flavor":"辛苦","meridians":["肺","膀胱"],"category":"泻肺药","historical_notes":"","herb_comparisons":["葶苈大枣泻肺汤（葶苈子+大枣）"]},
    {"name":"石韦","original":"苦、甘，微寒。归肺、膀胱经。利尿通淋，清热止血。","action":"石韦为利水通淋要药，清热止血。","dosage":"二至四钱。","contraindication":"无湿热者不宜。","clinical_notes":"倪海厦：石韦利水通淋，治石淋（肾结石）要药。配滑石、车前子增强利水之力。","nature_category":"微寒","flavor":"苦甘","meridians":["肺","膀胱"],"category":"利水药","historical_notes":"","herb_comparisons":[]},
    {"name":"大腹皮","original":"辛，微温。归脾、胃、大肠、小肠经。行气宽中，行水消肿。","action":"大腹皮为行气宽中要药，利水消肿。","dosage":"一至三钱。","contraindication":"气虚体弱者不宜。","clinical_notes":"倪海厦：大腹皮在分消汤中用一钱，属甘淡渗利药，用于腹水治疗。配合茯苓泽泻利水。","nature_category":"微温","flavor":"辛","meridians":["脾","胃","大肠","小肠"],"category":"理气药","historical_notes":"","herb_comparisons":[]},
    {"name":"芡实","original":"味甘淡，性平，无毒。固本益精要药，主泄泻遗精，带下白浊，治湿痹腰脊膝痛。","action":"芡实为益肾固精要药，健脾止泻。","dosage":"普通二至三钱。","contraindication":"生食动冷气，小儿不宜多食（难化），食芡必细嚼。","clinical_notes":"倪海厦：淡味能渗泄，是阳药，多吃没关系。芡实、薏仁、淮山、莲子都是甘淡味，常吃祛湿。微甘而涩能收湿气故健脾。颜色淡白入肾。","nature_category":"平","flavor":"甘淡","meridians":["脾","肾"],"category":"固涩药","historical_notes":"","herb_comparisons":[]},
    {"name":"莲子","original":"味甘涩，性平，无毒。健脾养胃清心固精，资益气血，主补中倍力，除烦养神，治白浊梦遗、女子崩带、疗久痢、脾虚泄泻。","action":"莲子为补脾止泻要药，养心安神。","dosage":"普通三至四钱。记得去芯否则吃多心烦。","contraindication":"生食过多微动冷气胀人，熟食过多涩大便，莲藕忌犯铁。","clinical_notes":"倪海厦：淡味平常可以多吃，祛湿。每天喝莲子汤可祛湿。莲子利小便排水后大便变干，吃时加蔗糖淮山冰糖润肠。记得去芯否则吃多心烦。莲子甘平无毒与诸疾无忤。","nature_category":"平","flavor":"甘涩","meridians":["脾","肾","心"],"category":"补益药","historical_notes":"","herb_comparisons":[]},
    {"name":"酸枣仁","original":"味酸，性平，无毒。宁心敛汗要药，主心腹寒热邪结气聚，烦心不眠，虚汗烦渴，治四肢酸痛湿痹，益肝养筋。","action":"酸枣仁为养心安神要药，敛汗生津。","dosage":"普通一钱至三钱。","contraindication":"肝胆心脾有实邪热者禁用（收敛故也）。","clinical_notes":"倪海厦：味酸有收敛之性，表虚或心里急躁可用酸枣仁收敛。治疗失眠取其收敛之性，经方有酸枣仁汤。能益肝养筋（酸味入肝，肝主筋）。","nature_category":"平","flavor":"酸","meridians":["心","肝","胆"],"category":"安神药","historical_notes":"","herb_comparisons":[]},
    {"name":"麦冬","original":"味甘，性寒，无毒。润肺清火要药，主治肺中伏火、痰多、心腹结气、肺弱胃弱、津少口渴、止咳嗽、疗肺病吐脓血。","action":"麦冬为润肺养阴要药，清心除烦。","dosage":"普通一钱至三钱。入补药酒浸良。","contraindication":"性微寒，虚寒泄泻及痘疮虚寒作泻者忌。","clinical_notes":"倪海厦：润肺清火要药，很多肺病都用到麦门冬且能止渴。干咳嘴巴干=麦门冬汤。辨证施治：不管西医诊断肺结核肺痨肺癌肺气肿，只要干咳嘴巴干舌苔黄腻就用麦门冬汤。眼睛发黄（眼白入肺，肺热）用麦门冬。女孩子多吃令人肥健美还能生小孩。经水枯乳汁不下用麦门冬滋润。","nature_category":"寒","flavor":"甘","meridians":["心","肺","胃"],"category":"补阴药","historical_notes":"","herb_comparisons":["麦门冬汤（麦冬+半夏+人参+甘草+粳米+大枣）"]},
    {"name":"黄柏","original":"味苦，性寒，无毒。除热杀虫坚肾益阴要药，主结热黄疸诸痿瘫痪，治诸疮痛泄痢下血，泻膀胱相火，疗淋浊白带，肠胃结热。","action":"黄柏为清热燥湿要药，泻相火。","dosage":"普通五分至二钱。","contraindication":"恶干漆伏硫磺，阴阳两虚脾胃薄弱者均忌。","clinical_notes":"倪海厦：膀胱热肾脏热、肾结石膀胱结石小便刺痛效果好。寒凉药可解毒杀菌去热。黄柏+苍术=去湿热（朱丹溪方）。得细辛泻膀胱火治口舌生疮。","nature_category":"寒","flavor":"苦","meridians":["肾","膀胱"],"category":"清热燥湿药","historical_notes":"","herb_comparisons":["黄柏+苍术（二妙散）治湿热","黄柏+知母（滋阴降火）"]},
    {"name":"饴糖","original":"甘，温。归脾、胃、肺经。补脾益气，缓急止痛，润肺止咳。","action":"饴糖为补中缓急要药，润肺止咳。","dosage":"一至二两，烊化冲服。","contraindication":"湿阻中满者不宜。","clinical_notes":"倪海厦：饴糖即麦芽糖，是小建中汤的核心组成。甘温入脾，开胃健脾，补脾虚津液不足。虚寒腹痛主方小建中汤中必用。饴糖很甜，药一下去脾阳马上起来。功能开胃让小孩爱吃东西，脾的津液不足靠饴糖。小建中汤加饴糖胃口大开。","nature_category":"温","flavor":"甘","meridians":["脾","胃","肺"],"category":"补益药","historical_notes":"","herb_comparisons":[]},
]

added = 0
for h in NEW_HERBS:
    name = h["name"]
    if name in names:
        print(f"SKIP (already exists): {name}")
        continue
    herbs.append(h)
    names.add(name)
    added += 1
    print(f"Added: {name}")

data['herbs'] = herbs
data['total'] = len(herbs)

with open('assets/data/herbs.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nAdded {added} herbs. Total now: {len(herbs)}")
